### ISSUE TITLE
Add instructions on installing the required Ruby version to the Readme.

### ISSUE THREAD

**Issue by cknoxrun** [omxhealth/drugbank-sample-apps#12]
Let them know to use RVM, rbenv, chruby, etc.

**Comment by petreman** [comment]
How's this sound? I think these ways of setting the version will work but I haven't tested them (I'm on Windows):

## Ruby

### Setting the Ruby Version
Ensure that you have Ruby 2.7.1 [installed](https://www.ruby-lang.org/en/downloads/).

Navigate to `drugbank-sample-apps/ruby`.

If you are using rbenv, Ruby 2.7.1 will be used automatically due to the `.ruby-version` file.

If you are using RVM, use the command
```bash
rvm use 2.7.1
```

If you are using chruby, use the command
```bash
chruby ruby-2.7.1
```
or if you have [auto-switching](https://github.com/postmodern/chruby/blob/master/README.md#auto-switching) enabled, the correct version will be used from the `.ruby-version` file.

### Running the app

First, ensure that [Bundler](https://bundler.io/) is installed.

 Install the necessary gems by using the command
```bash
bundle install
```

The app is then run with the command
```bash
bundle exec ruby app.rb
```

Visit the default address with the port given in the console to view the app.

**Comment by cknoxrun** [comment]
This sounds great! I guess with the docker config it becomes less necessary, but I still think it's good to have it.
